<?php

namespace App\Http\Controllers\API\User;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Log;

class LoginController extends Controller
{
    public function login(Request $request)
    {
        $login = $request->validate([
            'email' => 'required',
            'password'=> 'required',
            // 'companyId' => 'required',
        ]);
        if (!Auth::attempt($login)){
            return response()->json(['message' => 'The email or password you’ve entered is incorrect.'], 401);
        }
        $user = Auth::user();
        $user = User::find($user['id']);
    
        $ObjToken = $user->createToken('Personal Access Token');
        $token = $user->createToken('Personal Access Token')->accessToken;
        $expiration = $ObjToken->token->expires_at->diffInSeconds(Carbon::now());
        
        Log::debug($user->id);

        // check if manager
        $isManager = DB::select("SELECT IFNULL((SELECT TRUE FROM general.`systemreportingmanager` a WHERE a.`RMID` = $user->id LIMIT 1), FALSE) AS isManager");
        $isManager = $isManager[0]->isManager;

        // get user joined company
        $companies = $this->showCompanies($user->id);

        


        $userData = array('user' => $user, 'Personal_Access_Token' => $token, 'expires_at' => $expiration, 'isManager' => $isManager, 'company' => $companies );
        
  
        return response()->json($userData);
    }


    public function profile(){
        $user_data = Auth::user();
    //    return User::all();
        return response()->json([
            'status' => true,
            'message' => 'user data',
            'data' => $user_data
        ]);

    // return '1';


    }

    public function logout(Request $request)
    {
        $token = $request->user()->token();
        $token->revoke();
        $token->delete();
        // $request->user()->token()->revoke();
        $response = ['message' => 'You have been successfully logged out!'];
        return response($response, 200);
        // return response()->json(['token' =>  $request->user()]);
    }

    public function showCompanies($id){
        $companies = DB::select("SELECT 
        title_id AS companyID,
        title_name AS companyName 
      FROM
        general.`project_title` a 
        INNER JOIN general.`allowedcmp` b 
          ON (a.`title_id` = b.`CID`) 
      WHERE b.`UID` = $id");

        return $companies;
      
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }


    public function sync(){
        $data = [



['name' => 'Abejuela, Excel B.',
'email' => 'EXCEL.ABEJUELA@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Excel',
'lname' => 'Abejuela',
'department' => 'Customer Support',
'positionName' => 'Technical Support Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '180',
'employee_id' => '607'],
['name' => 'Agudo, Alfredo A.',
'email' => 'ALFREDO.AGUDO@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Alfredo',
'lname' => 'Agudo',
'department' => 'Operations ',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '83',
'employee_id' => '2'],
['name' => 'Aguilar, Jeross',
'email' => 'JEROSS.AGUILAR@CYLIX.PH',
'password' => bcrypt('Cylix1989'),
'fname' => 'Jeross',
'lname' => 'Aguilar',
'department' => 'Human Resource and Compliance',
'positionName' => 'Legal Compliance Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '70',
'employee_id' => '190'],
['name' => 'Alfonso, Arian A. ',
'email' => 'arian.alfonso@cylix.ph',
'password' => bcrypt('arianalfonso'),
'fname' => 'Arian',
'lname' => 'Alfonso',
'department' => 'Projects Management',
'positionName' => 'CAD Operator',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '130',
'employee_id' => '530'],
['name' => 'Almiñana, Ana Jorgenah M.',
'email' => 'ANA.ALMINANA@CYLIX.PH',
'password' => bcrypt('Kisses1054'),
'fname' => 'Ana Jorgenah',
'lname' => 'Almiñana',
'department' => 'Sales',
'positionName' => 'Sales and Supply Chain Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '134',
'employee_id' => '561'],
['name' => 'Almiñana, Ana Jorgenah M.',
'email' => 'ANA.ALMINANA.DEL@CYLIX.PH',
'password' => bcrypt('Kisses1054'),
'fname' => 'Ana Jorgenah',
'lname' => 'Almiñana',
'department' => 'Sales',
'positionName' => 'Sales and Supply Chain Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '203',
'employee_id' => '561'],
['name' => 'Amado, Carry Joy O.',
'email' => 'CARRYJOY.AMADO@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Carry Joy',
'lname' => 'Amado',
'department' => 'Operations ',
'positionName' => 'Operations Head',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '4',
'employee_id' => '8'],
['name' => 'Archivido, Jay O.',
'email' => 'JAY.ARCHIVIDO@CYLIX.PH',
'password' => bcrypt('Archie020110'),
'fname' => 'Jay',
'lname' => 'Archivido',
'department' => 'Operations Management',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '192',
'employee_id' => '721'],
['name' => 'Asi, Bhon Jeric M.',
'email' => 'JERIC.ASI@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Bhon Jeric',
'lname' => 'Asi',
'department' => 'Projects Management',
'positionName' => 'Project Management Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '231',
'employee_id' => '819'],
['name' => 'Bacanto, John Glenn P.',
'email' => 'john.bacanto@cylix.ph',
'password' => bcrypt('halflife0507!'),
'fname' => 'John Glenn',
'lname' => 'Bacanto',
'department' => 'Quality, Safety, Health and Environment',
'positionName' => 'Company Nurse',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '191',
'employee_id' => '718'],
['name' => 'Banaticla, Errol V.',
'email' => 'ERROL.BANATICLA@CYLIX.PH',
'password' => bcrypt('Ethan2425172210cha'),
'fname' => 'Errol',
'lname' => 'Banaticla',
'department' => 'Quality, Safety, Health and Environment',
'positionName' => 'QHSE Head',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '6',
'employee_id' => '19'],
['name' => 'Bantolo, Julius O.',
'email' => 'JULIUS.BANTOLO@CYLIX.PH',
'password' => bcrypt('jigajigz07'),
'fname' => 'Julius',
'lname' => 'Bantolo',
'department' => 'Operations ',
'positionName' => 'Operations Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '88',
'employee_id' => '20'],
['name' => 'Belarmino, Gerardo C.',
'email' => 'GERARDO.BELARMINO@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Gerardo',
'lname' => 'Belarmino',
'department' => 'Supply Chain Management',
'positionName' => 'Company Driver',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '196',
'employee_id' => '722'],
['name' => 'Belotindos, James G.',
'email' => 'JAMES.BELOTINDOS@CYLIX.PH',
'password' => bcrypt('kIESHA143'),
'fname' => 'James',
'lname' => 'Belotindos',
'department' => 'Sales',
'positionName' => 'Administrative Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '178',
'employee_id' => '673'],
['name' => 'Benitez, Emilio Jr.Jr. M.',
'email' => 'EMILIO.BENITEZ@CYLIX.PH',
'password' => bcrypt('IVmgu652'),
'fname' => 'Emilio',
'lname' => 'Benitez',
'department' => 'Operations ',
'positionName' => 'Leadman',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '89',
'employee_id' => '23'],
['name' => 'Benito, Missy',
'email' => 'MISSY.BENITO@CYLIX.PH',
'password' => bcrypt('hrMB@1998'),
'fname' => 'Missy',
'lname' => 'Benito',
'department' => 'Human Resource and Legal Compliance',
'positionName' => 'Human Resource Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '200',
'employee_id' => '728'],
['name' => 'Betache, Glenn',
'email' => 'glenn.betache@cylix.ph',
'password' => bcrypt('Letmein2021'),
'fname' => 'Glenn',
'lname' => 'Betache',
'department' => 'Operations ',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '216',
'employee_id' => '780'],
['name' => 'Briones, Allien Richard  .',
'email' => 'ALLEN.BRIONES@CYLIX.PH',
'password' => bcrypt('bT3ch2011)/'),
'fname' => 'Allien Richard',
'lname' => 'Briones',
'department' => 'Projects Management',
'positionName' => 'Project Managerment Engineer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '253',
'employee_id' => '847'],
['name' => 'Bual, Ma. Lorimar D.',
'email' => 'LORIMAR.DONES@CYLIX.PH',
'password' => bcrypt('August161991'),
'fname' => 'Ma. Lorimar',
'lname' => 'Bual',
'department' => 'Accounting and Finance',
'positionName' => 'Accounting Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '7',
'employee_id' => '25'],
['name' => 'Cahucom, Portia A.',
'email' => 'PORTIA.CAHUCOM@CYLIX.PH',
'password' => bcrypt('portia123'),
'fname' => 'Portia',
'lname' => 'Cahucom',
'department' => 'Information Technology',
'positionName' => 'Lead System Engineer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '177',
'employee_id' => '245'],
['name' => 'Calago, Anna Fe',
'email' => 'annafe.calago@cylix.ph',
'password' => bcrypt('Letmein2021'),
'fname' => 'Anna Fe',
'lname' => 'Calago',
'department' => 'Projects Management',
'positionName' => 'Document Controller',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '228',
'employee_id' => '821'],
['name' => 'Calderon, Rodalyn C.',
'email' => 'RODALYN.CALDERON@CYLIX.PH',
'password' => bcrypt('151210asd'),
'fname' => 'Rodalyn',
'lname' => 'Calderon',
'department' => 'Supply Chain Management',
'positionName' => 'Supply Chain Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '9',
'employee_id' => '30'],
['name' => 'Calimlim, Rolly E.',
'email' => 'ROLLY.CALIMLIM@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Rolly',
'lname' => 'Calimlim',
'department' => 'Supply Chain Management',
'positionName' => 'MM Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '115',
'employee_id' => '31'],
['name' => 'Calipayan, Arnel P.',
'email' => 'ARNEL.CALIPAYAN@CYLIX.PH',
'password' => bcrypt('ArCal2021'),
'fname' => 'Arnel',
'lname' => 'Calipayan',
'department' => 'Operations ',
'positionName' => 'Operations Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '182',
'employee_id' => '696'],
['name' => 'Carpio, Emmanuel A.',
'email' => 'EMMANUEL.CARPIO@CYLIX.PH',
'password' => bcrypt('75Jusjeddim11'),
'fname' => 'Emmanuel',
'lname' => 'Carpio',
'department' => 'Operations ',
'positionName' => 'Operations Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '60',
'employee_id' => '34'],
['name' => 'Casinsinan, Maria Kristine C.',
'email' => 'KRISTINE.CASINSINAN@CYLIX.PH',
'password' => bcrypt('Kambal041112'),
'fname' => 'Maria Kristine',
'lname' => 'Casinsinan',
'department' => 'Projects Management',
'positionName' => 'Project Management Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '184',
'employee_id' => '707'],
['name' => 'Catapang, Dionisio C.',
'email' => 'DIONISIO.CATAPANG@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Dionisio',
'lname' => 'Catapang',
'department' => 'Operations ',
'positionName' => 'Operations Head',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '92',
'employee_id' => '39'],
['name' => 'Ceballos, Rosevir Jr.Jr. M.',
'email' => 'ROSEVIR.CEBALLOS@CYLIX.PH',
'password' => bcrypt('!LetHf4faedfeexl14iN@123!'),
'fname' => 'Rosevir',
'lname' => 'Ceballos',
'department' => 'Information Technology',
'positionName' => 'IT Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '136',
'employee_id' => '238'],
['name' => 'Chingcuangco, Rene',
'email' => 'RENE.CHINGCUANGCO@CYLIX.PH',
'password' => bcrypt('Wagkalimutan149'),
'fname' => 'Rene',
'lname' => 'Chingcuangco',
'department' => 'Management',
'positionName' => 'Director for Special Projects',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '14',
'employee_id' => '41'],
['name' => 'Chua Lee, Carrie A.',
'email' => 'CARRIE@CYLIX.PH',
'password' => bcrypt('Accounting2014'),
'fname' => 'Carrie',
'lname' => 'Chua Lee',
'department' => 'Accounting and Finance',
'positionName' => 'Accounting and Finance Head',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '12',
'employee_id' => '43'],
['name' => 'Chua, Konrad A.',
'email' => 'KONRAD.CHUA@CYLIX.PH',
'password' => bcrypt('letK0nradin'),
'fname' => 'Konrad',
'lname' => 'Chua',
'department' => 'Management',
'positionName' => 'Managing Director',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '11',
'employee_id' => '42'],
['name' => 'Cielo, Criselda N.',
'email' => 'CRISELDA.CIELO@CYLIX.PH',
'password' => bcrypt('letmein'),
'fname' => 'Criselda',
'lname' => 'Cielo',
'department' => 'Sales',
'positionName' => 'Senior Sales Executive',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '13',
'employee_id' => '44'],
['name' => 'Corpuz, John Keivin S.',
'email' => 'JOHN.CORPUZ@CYLIX.PH',
'password' => bcrypt('10211994mybirthdate'),
'fname' => 'John Keivin',
'lname' => 'Corpuz',
'department' => 'Projects Management',
'positionName' => 'Project Management Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '15',
'employee_id' => '47'],
['name' => 'Cortez, Paul Iverson G.',
'email' => 'PAUL.CORTEZ@CYLIX.PH',
'password' => bcrypt('ZetrocLuap!23'),
'fname' => 'Paul Iverson',
'lname' => 'Cortez',
'department' => 'Information Technology',
'positionName' => 'IT Network Administrator',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '186',
'employee_id' => '710'],
['name' => 'Cruz, Evelyn  C.',
'email' => 'EVELYN.CRUZ@CYLIX.PH',
'password' => bcrypt('Baguio2020'),
'fname' => 'Evelyn ',
'lname' => 'Cruz',
'department' => 'Sales',
'positionName' => 'Sales Manager',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '197',
'employee_id' => '736'],
['name' => 'Dee, Leonard M.',
'email' => 'LEONARD.DEE@CYLIX.PH',
'password' => bcrypt('josemiguel0824'),
'fname' => 'Leonard',
'lname' => 'Dee',
'department' => 'Information Technology',
'positionName' => 'IT Network Administrator',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '149',
'employee_id' => '583'],
['name' => 'Delos Reyes, Emmanuel',
'email' => 'EMMANUEL.DELOSREYES@CYLIX.PH',
'password' => bcrypt('Emman259805'),
'fname' => 'Emmanuel',
'lname' => 'Delos Reyes',
'department' => 'Accounting and Finance',
'positionName' => 'Audit Head',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '150',
'employee_id' => '610'],
['name' => 'Embuscado, Aireen Grace O.',
'email' => 'AIREEN.EMBUSCADO@CYLIX.PH',
'password' => bcrypt('aiko0528'),
'fname' => 'Aireen Grace',
'lname' => 'Embuscado',
'department' => 'Sales',
'positionName' => 'Senior Sales Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '18',
'employee_id' => '59'],
['name' => 'Embuscado, Aireen Grace O. - Delegate',
'email' => 'AIREEN.EMBUSCADO.DEL@CYLIX.PH',
'password' => bcrypt('aiko0528'),
'fname' => 'Aireen Grace',
'lname' => 'Embuscado',
'department' => 'Sales',
'positionName' => 'Senior Sales Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '160',
'employee_id' => '59'],
['name' => 'Esguerra, Norie Val A.',
'email' => 'NORIE.ESGUERRA@CYLIX.PH',
'password' => bcrypt('7275300Nor'),
'fname' => 'Norie Val',
'lname' => 'Esguerra',
'department' => 'Customer Support',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '207',
'employee_id' => '706'],
['name' => 'Flores, Hibraham',
'email' => 'HIBRAHAM.FLORES@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Hibraham',
'lname' => 'Flores',
'department' => 'Operations ',
'positionName' => 'Company Driver',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '202',
'employee_id' => '747'],
['name' => 'Gelarzo, Rey N.',
'email' => 'REY.GELARZO@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Rey',
'lname' => 'Gelarzo',
'department' => 'Supply Chain Management',
'positionName' => 'Warehouseman',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '119',
'employee_id' => '72'],
['name' => 'Gersava, Joshua M.',
'email' => 'JOSHUA.GERSAVA@CYLIX.PH',
'password' => bcrypt('Dell2021!'),
'fname' => 'Joshua',
'lname' => 'Gersava',
'department' => 'Sales',
'positionName' => 'Solutions Engineer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '209',
'employee_id' => '775'],
['name' => 'Go, Dominic Byron T.',
'email' => 'DOMINIC.GO@CYLIX.PH',
'password' => bcrypt('dd100800'),
'fname' => 'Dominic Byron',
'lname' => 'Go',
'department' => 'Management',
'positionName' => 'Executive Director',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '19',
'employee_id' => '75'],
['name' => 'Guavez, Wilson A.',
'email' => 'WILSON.GUAVEZ@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Wilson',
'lname' => 'Guavez',
'department' => 'Operations ',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '99',
'employee_id' => '77'],
['name' => 'Hicban, Kristele Anne',
'email' => 'kristele.hicban@cylix.ph',
'password' => bcrypt('Letmein2021'),
'fname' => 'Kristele Anne',
'lname' => 'Hicban',
'department' => 'Projects Management',
'positionName' => 'Document Controller',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '257',
'employee_id' => '853'],
['name' => 'Inot, Rodgie',
'email' => 'rodgie.inot@cylix.ph',
'password' => bcrypt('Letmein2021'),
'fname' => 'Rodgie',
'lname' => 'Inot',
'department' => 'Operations ',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '215',
'employee_id' => '779'],
['name' => 'Ipac, Oliver  L.',
'email' => 'OLIVER.IPAC@CYLIX.PH',
'password' => bcrypt('Section2e'),
'fname' => 'Oliver ',
'lname' => 'Ipac',
'department' => 'Operations Management',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '190',
'employee_id' => '609'],
['name' => 'Izon, Nedilyn B.',
'email' => 'NEDILYN.IZON@CYLIX.PH',
'password' => bcrypt('*ShainaKevin*'),
'fname' => 'Nedilyn',
'lname' => 'Izon',
'department' => 'Accounting and Finance',
'positionName' => 'Payroll Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '66',
'employee_id' => '177'],
['name' => 'Jaropojop, Jenine S.',
'email' => 'JENINE.JAROPOJOP@CYLIX.PH',
'password' => bcrypt('july211994'),
'fname' => 'Jenine',
'lname' => 'Jaropojop',
'department' => 'Accounting and Finance',
'positionName' => 'Accounting Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '154',
'employee_id' => '635'],
['name' => 'Joson, Romero P.',
'email' => 'ROMERO.JOSON@CYLIX.PH',
'password' => bcrypt('Welcome2019'),
'fname' => 'Romero',
'lname' => 'Joson',
'department' => 'Project Management',
'positionName' => 'Senior Project Engineer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '153',
'employee_id' => '630'],
['name' => 'Ke-E, Gilbert P.',
'email' => 'gilbert.kee@cylix.ph',
'password' => bcrypt('!LetmeiN@123!'),
'fname' => 'Gilbert',
'lname' => 'Ke-E',
'department' => 'Quality, Safety, Health and Environment',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '171',
'employee_id' => '85'],
['name' => 'Lapitan, Millard D.',
'email' => 'MILLARD.LAPITAN@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Millard',
'lname' => 'Lapitan',
'department' => 'Information Technology',
'positionName' => 'Lead System Engineer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '140',
'employee_id' => '239'],
['name' => 'Lim, Gabriel Elijah O.',
'email' => 'GABRIEL.LIM@CYLIX.PH',
'password' => bcrypt('Gabbo!14'),
'fname' => 'Gabriel Elijah',
'lname' => 'Lim',
'department' => 'Operations ',
'positionName' => 'Senior Operations Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '217',
'employee_id' => '786'],
['name' => 'Lorenzo, Aldrin Francis G.',
'email' => 'ALDRIN.LORENZO@CYLIX.PH',
'password' => bcrypt('letmein'),
'fname' => 'Aldrin Francis',
'lname' => 'Lorenzo',
'department' => 'Information Technology',
'positionName' => 'IT Network Administrator',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '226',
'employee_id' => '740'],
['name' => 'Luberia, John Carlo L.',
'email' => 'CARLO.LUBERIA@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'John Carlo',
'lname' => 'Luberia',
'department' => 'Operations',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '169',
'employee_id' => '93'],
['name' => 'Macanas, Markeen Abrielle C.',
'email' => 'MARKEEN.MACANAS@CYLIX.PH',
'password' => bcrypt('041694MrknMcns'),
'fname' => 'Markeen Abrielle',
'lname' => 'Macanas',
'department' => 'Projects Management',
'positionName' => 'Senior Project Engineer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '25',
'employee_id' => '95'],
['name' => 'Macanas, Markeen Abrielle C. - Delegate',
'email' => 'MARKEEN.MACANAS.DEL@CYLIX.PH',
'password' => bcrypt('041694MrknMcns'),
'fname' => 'Markeen Abrielle',
'lname' => 'Macanas',
'department' => 'Projects Management',
'positionName' => 'Senior Project Engineer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '161',
'employee_id' => '95'],
['name' => 'Macayan, Mark Joseph T.',
'email' => 'JOSEPH.MACAYAN@CYLIX.PH',
'password' => bcrypt('153427220M@rk'),
'fname' => 'Mark Joseph',
'lname' => 'Macayan',
'department' => 'Sales',
'positionName' => 'Pre-Sales Engineer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '69',
'employee_id' => '189'],
['name' => 'Marin, Arondael M.',
'email' => 'ARONDAEL.MARIN@CYLIX.PH',
'password' => bcrypt('Cap2529!'),
'fname' => 'Arondael',
'lname' => 'Marin',
'department' => 'Operations ',
'positionName' => 'Operations Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '185',
'employee_id' => '702'],
['name' => 'Martinez, Clyde Y. ',
'email' => 'clyde.martinez@cylix.ph',
'password' => bcrypt('mh!e060610'),
'fname' => 'Clyde',
'lname' => 'Martinez',
'department' => 'Quality, Safety, Health and Environment',
'positionName' => 'Safety Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '146',
'employee_id' => '205'],
['name' => 'Mitra, Richard D.',
'email' => 'richard.mitra@cylix.ph',
'password' => bcrypt('Letmein2021'),
'fname' => 'Richard',
'lname' => 'Mitra',
'department' => 'Operations ',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '227',
'employee_id' => '820'],
['name' => 'Navalta, Harold T.',
'email' => 'HAROLD.NAVALTA@CYLIX.PH',
'password' => bcrypt('Dax27610'),
'fname' => 'Harold',
'lname' => 'Navalta',
'department' => 'Operations ',
'positionName' => 'Leadman',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '111',
'employee_id' => '113'],
['name' => 'Pailanan, Junmark J.',
'email' => 'JUNMARK.PAILANAN@CYLIX.PH',
'password' => bcrypt('2011cylix'),
'fname' => 'Junmark',
'lname' => 'Pailanan',
'department' => 'Customer Support',
'positionName' => 'Senior Customer Service Specialist',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '30',
'employee_id' => '123'],
['name' => 'Pailanan, Junmark J.',
'email' => 'JUNMARK.PAILANAN.DEL@CYLIX.PH',
'password' => bcrypt('Letmein2019'),
'fname' => 'Junmark',
'lname' => 'Pailanan',
'department' => 'Customer Support',
'positionName' => 'Senior Customer Service Specialist',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '162',
'employee_id' => '123'],
['name' => 'Papa, Randy B.',
'email' => 'RANDY.PAPA@CYLIX.PH',
'password' => bcrypt('NewJob2021'),
'fname' => 'Randy',
'lname' => 'Papa',
'department' => 'Customer Support',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '206',
'employee_id' => '705'],
['name' => 'Patawaran, Erickson P.',
'email' => 'erickson.patawaran@cylix.ph',
'password' => bcrypt('Letmein2021'),
'fname' => 'Erickson',
'lname' => 'Patawaran',
'department' => 'Operations ',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '255',
'employee_id' => '850'],
['name' => 'Perez, Aaron Christopher D.',
'email' => 'AARON.PEREZ@CYLIX.PH',
'password' => bcrypt('letmein'),
'fname' => 'Aaron Christopher',
'lname' => 'Perez',
'department' => 'Projects Management',
'positionName' => 'CAD Operator',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '131',
'employee_id' => '551'],
['name' => 'Persigas, Rolito H.',
'email' => 'ROLITO.PERSIGAS@CYLIX.PH',
'password' => bcrypt('Letmein2020'),
'fname' => 'Rolito',
'lname' => 'Persigas',
'department' => 'Supply Chain Management',
'positionName' => 'Company Driver',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '172',
'employee_id' => '657'],
['name' => 'Pineda, Roger D.',
'email' => 'ROGER.PINEDA@CYLIX.PH',
'password' => bcrypt('1206312jay'),
'fname' => 'Roger',
'lname' => 'Pineda',
'department' => 'Quality, Safety, Health and Environment',
'positionName' => 'Safety and Quality Assurance',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '166',
'employee_id' => '130'],
['name' => 'Regidor, Jan Carlo O.',
'email' => 'carlo.regidor@cylix.ph',
'password' => bcrypt('idolJesus4ever'),
'fname' => 'Jan Carlo',
'lname' => 'Regidor',
'department' => 'Information Technology',
'positionName' => 'IT Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '210',
'employee_id' => '770'],
['name' => 'Roldan, Mark Jasper A.',
'email' => 'MARK.ROLDAN@CYLIX.PH',
'password' => bcrypt('Markleonardroldan23'),
'fname' => 'Mark Jasper',
'lname' => 'Roldan',
'department' => 'Projects Management',
'positionName' => 'Project Management Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '204',
'employee_id' => '756'],
['name' => 'Roncales, Eleazar S.',
'email' => 'ELEAZAR.RONCALES@CYLIX.PH',
'password' => bcrypt('Esar@cylix.1101'),
'fname' => 'Eleazar',
'lname' => 'Roncales',
'department' => 'Project Management',
'positionName' => 'CAD Operator',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '143',
'employee_id' => '573'],
['name' => 'Salazar, Mark Anthony L.',
'email' => 'MARK@CYLIX.PH',
'password' => bcrypt('!LetmeiN@CTI!'),
'fname' => 'Mark Anthony',
'lname' => 'Salazar',
'department' => 'Business Development',
'positionName' => 'Head of Business Development for Central Luzon',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '34',
'employee_id' => '146'],
['name' => 'Santos, Rizalinio N.',
'email' => 'RIZALINIO.SANTOS@CYLIX.PH',
'password' => bcrypt('letmein'),
'fname' => 'Rizalinio',
'lname' => 'Santos',
'department' => 'Supply Chain Management',
'positionName' => 'Warehouseman',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '158',
'employee_id' => '641'],
['name' => 'Sario, Ramiro',
'email' => 'ramiro.sario@cylix.ph',
'password' => bcrypt('Letmein2021'),
'fname' => 'Ramiro',
'lname' => 'Sario',
'department' => 'Operations ',
'positionName' => 'Technical Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '254',
'employee_id' => '849'],
['name' => 'Sayta, Jobel R.',
'email' => 'JOBEL.SAYTA@CYLIX.PH',
'password' => bcrypt('boss1992'),
'fname' => 'Jobel',
'lname' => 'Sayta',
'department' => 'Sales',
'positionName' => 'Sales Coordinator',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '41',
'employee_id' => '152'],
['name' => 'Sayta, Jobel R. - Delegate',
'email' => 'JOBEL.SAYTA.DEL@CYLIX.PH',
'password' => bcrypt('letmein2020'),
'fname' => 'Jobel',
'lname' => 'Sayta',
'department' => 'Sales',
'positionName' => 'Sales Coordinator',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '175',
'employee_id' => '152'],
['name' => 'Solis, Blessy Joy T.',
'email' => 'BLESSY.SOLIS@CYLIX.PH',
'password' => bcrypt('Mommyblessy08!'),
'fname' => 'Blessy Joy',
'lname' => 'Solis',
'department' => 'Supply Chain Management',
'positionName' => 'Supply Chain Staff',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '214',
'employee_id' => '785'],
['name' => 'Soriano, Jhonalyn C.',
'email' => 'JHONALYN.SORIANO@CYLIX.PH',
'password' => bcrypt('Kierran0912@'),
'fname' => 'Jhonalyn',
'lname' => 'Soriano',
'department' => 'Sales',
'positionName' => 'Sales Coordinator',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '167',
'employee_id' => '647'],
['name' => 'System Admiinstrator',
'email' => 'ADMIN',
'password' => bcrypt('123'),
'fname' => 'Administrator',
'lname' => '',
'department' => 'IT Department',
'positionName' => 'System Admin',
'companyId' => '0',
'companyName' => '',
'id' => '1',
'employee_id' => '-1'],
['name' => 'Tantiongco, Karen Rose D.',
'email' => 'KAREN.TANTIONGCO@CYLIX.PH',
'password' => bcrypt('Letmein2021'),
'fname' => 'Karen Rose',
'lname' => 'Tantiongco',
'department' => 'Sales',
'positionName' => 'Account Manager',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '198',
'employee_id' => '732'],
['name' => 'Tapang, Marvie Ann A.',
'email' => 'MARVIE.TAPANG@CYLIX.PH',
'password' => bcrypt('Jomskie110813'),
'fname' => 'Marvie Ann',
'lname' => 'Tapang',
'department' => 'Operations Management',
'positionName' => 'Quality Assurance Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '47',
'employee_id' => '160'],
['name' => 'Tiglao, Camille Louise',
'email' => 'camille.tiglao@cylix.ph',
'password' => bcrypt('zoWy51616'),
'fname' => 'Camille Louise',
'lname' => 'Tiglao',
'department' => 'Projects Management',
'positionName' => 'Project Managerment Engineer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '256',
'employee_id' => '852'],
['name' => 'Villarin, Alexis S.',
'email' => 'ALEXIS.VILLARIN@CYLIX.PH',
'password' => bcrypt('welcome123!'),
'fname' => 'Alexis',
'lname' => 'Villarin',
'department' => 'Information Technology',
'positionName' => 'IT Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '201',
'employee_id' => '743'],
['name' => 'Yu, Dennis C.',
'email' => 'DENNIS.YU@CYLIX.PH',
'password' => bcrypt('Letmein2019'),
'fname' => 'Dennis',
'lname' => 'Yu',
'department' => 'Operations',
'positionName' => 'Senior Operations Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '132',
'employee_id' => '557'],
['name' => 'Yu, Dennis C.',
'email' => 'SCM.HEAD@CYLIX.PH',
'password' => bcrypt('Letmein2019'),
'fname' => 'Dennis',
'lname' => 'Yu',
'department' => 'Operations',
'positionName' => 'Senior Operations Officer',
'companyId' => '1',
'companyName' => 'Cylix Technologies, Inc.',
'id' => '135',
'employee_id' => '557'],

        ];
        
        $data = DB::table('ctierp.users')->insert($data);
        return response($data);
    }



    
}
